CREATE DATABASE "ProjetoHuilson"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE CAIXA_DE_AGUA (
        ID SERIAL PRIMARY KEY,
        MARCA VARCHAR,
        MODELO VARCHAR,
        DIMENSAO DOUBLE PRECISION[],
        COR VARCHAR,
        MATERIAL VARCHAR,
        FORMATO VARCHAR,
        PRECO DECIMAL,
)

CREATE TABLE SALDO (
    ID SERIAL PRIMARY KEY,
    VALOR_SALDO DECIMAL
)

INSERT INTO SALDO(VALOR_SALDO) VALUES(1000);

CREATE TABLE ESTOQUE_CAIXA_DE_AGUA(
    ID INTEGER PRIMARY KEY,
    QUANTIDADE INTEGER,

    FOREIGN KEY (ID) REFERENCES CAIXA_DE_AGUA(id)
)

CREATE OR REPLACE FUNCTION criar_estoque_automatico()
RETURNS TRIGGER AS $$
BEGIN
INSERT INTO ESTOQUE_CAIXA_DE_AGUA (id, quantidade)
VALUES (NEW.id, 0);

RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_criar_estoque
    AFTER INSERT ON CAIXA_DE_AGUA
    FOR EACH ROW
    EXECUTE FUNCTION criar_estoque_automatico();